"""empty message

Revision ID: 1b6125908d5a
Revises: bb488872a057
Create Date: 2016-05-17 16:06:12.376157

"""

# revision identifiers, used by Alembic.
revision = '1b6125908d5a'
down_revision = 'bb488872a057'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
